#### Bài tập 1: Numpy cơ bản


In [27]:
import numpy as np

In [28]:
# Câu 3:
arr = np.arange(0, 10)
print(arr[arr % 2 == 1])

[1 3 5 7 9]


In [30]:
# Câu 4
arr = np.arange(0, 10)
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [31]:
# cau 5:
arr = np.arange(10)
arr_2d = arr.reshape(2, -1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [33]:
# cau 6:
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=0)
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [34]:
# cau 7:
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate([arr1, arr2], axis=1)
print(c)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [35]:
# cau 8
arr = np.array([1, 2, 3])
print(np.repeat(arr, 3))
print(np.tile(arr, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [36]:
# cau 9
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a >= 5) & (a <= 10))
print(a[index])

[ 6  9 10]


In [37]:
# cau 10
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y


a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max = np.vectorize(maxx, otypes=[float])
print(pair_max(a, b))

[6. 7. 9. 8. 9. 7. 5.]


In [38]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
print(np.where(a < b, b, a))

[6 7 9 8 9 7 5]


#### Bài tập 2: Xử lý ảnh

In [22]:
import numpy as np
import matplotlib.image as mpimg

In [23]:
# câu 12: chuyển ảnh màu sang ảnh xám bằng phương pháp Lightness
img = mpimg.imread('./dog.jpeg')
gray_img_01 = (np.max(img, axis=2) + np.min(img, axis=2)) / 2
gray_img_01[0, 0]

102.5

In [24]:
# Câu 13: chuyển ảnh màu sang ảnh xám bằng phương pháp Average
img = mpimg.imread('./dog.jpeg')
# gray_img_02 = np.sum(img, axis=2) / 3
gray_img_02 = np.average(img, axis=2)
gray_img_02[0, 0]

107.66666666666667

In [25]:
# Câu 14: chuyển ảnh màu sang ảnh xám bằng phương pháp Luminosity
img = mpimg.imread('./dog.jpeg')
gray_img_03 = 0.21*img[:, :, 0] + 0.72*img[:, :, 1] + 0.07*img[:, :, 2]
gray_img_03[0, 0]

126.22999999999999

#### Bài tập 3: Phân tích dữ liệu dạng bảng


In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('./advertising.csv')
data = df.to_numpy()

In [11]:
# Câu 15: giá trị lớn nhất và chỉ mục tương ứng trên cột Sales
sales_column = data[:, 3]
max_value = sales_column.max()
indices = sales_column.argmax()
print(f'Max: {max_value} - Index: {indices}')

Max: 27.0 - Index: 175


In [5]:
# Câu 16: giá trị trung bình cột TV
data = df['TV'].to_numpy()
np.mean(data)

147.0425

In [45]:
# Câu 17: Số lượng bản ghi có giá trị tại cột Sales >= 20
data = df['Sales'][df['Sales'] >= 20]
print(data.count())

40


In [53]:
# Câu 18: Giá trị trung bình của cột Radio thoả mãn điều kiện giá trị tương ứng trên cột Sales >= 15
data = df[df['Sales'] >= 15]['Radio'].mean()
# print(np.average(data))
print(data)

26.22293577981651


In [3]:
# Câu 19: Tính tổng các giá trị của cột Newspaper sao cho giá trị của nó loứn hƠn giá trị trung bình của cột Newspaper
average_newspaper = df['Newspaper'].mean()
data = df['Sales'][df['Newspaper'] > average_newspaper]
print(data.sum())

1405.1


In [6]:
# Câu 20:
sales_column = df['Sales']
mean_sales = sales_column.mean()
# scores = ['Good' if value > mean_sales else (
#     'Bad' if value < mean_sales else 'Average') for value in sales_column]
scores = np.where(df['Sales'] > mean_sales, 'Good', np.where(
    df['Sales'] < mean_sales, 'Bad', 'Average'))
print(scores[7:10])

['Bad' 'Bad' 'Good']


In [7]:
# Câu 21: index_closest_value
sales_column = df['Sales']
mean_sales = sales_column.mean()
index_closest_value = np.argmin(np.abs(sales_column - mean_sales))
closest_value = sales_column[index_closest_value]
scores = np.where(df['Sales'] > closest_value, 'Good', np.where(
    df['Sales'] < closest_value, 'Bad', 'Average'))
print(scores[7:10])

['Bad' 'Bad' 'Good']
