### 1.1 Length of a vector

- Vector: **v** = $[v_1, v_2, ..., v_n]^T$
- Length of a vector: $\left \| v \right \| = \sqrt{v_1^2 + v_2^2 + ... + v_n^2}$


In [1]:
import numpy as np

In [2]:
def compute_vector_length(vector):
    len_of_vector = np.sqrt(vector.dot(vector))
    return len_of_vector

In [3]:
vector = np.array([-2, 4, 9, 21])
print(np.sqrt(vector.dot(vector)))

23.280893453645632


### 1. 2 Dot product

- Vector: **v** = $\begin{bmatrix}
v_1
\\ v_2
\\ ...
\\v_n
\end{bmatrix}$
  <span style="margin-left: 32px;"></span>
  **u** = $\begin{bmatrix}
u_1
\\ u_2
\\ ...
\\u_n
\end{bmatrix}$

- Dot Product: **v** . **u** = _v_1 \* u_1 + v_2 \* u_2 + ... + v_n \* u_n_


In [4]:
def compute_dot_product(vector1, vector2):
    result = vector1.dot(vector2)
    return result

In [5]:
v1 = np.array([0, 1, -1, 2])
v2 = np.array([2, 5, 1, 0])
result = compute_dot_product(v1, v2)
print(round(result, 2))

4


### 1.3. Multiplying a vector by a matrix

- Matrix: A = $\begin{bmatrix}
 a_{11} & \dots & a_{1n} \\
 \vdots & \ddots & \vdots \\
 a_{m1} & \dots & a_{mn}
\end{bmatrix}$, **A** $\epsilon R^{nm}$

- Vector: **v** = $\begin{bmatrix}
v_1
\\ v_2
\\ ...
\\v_n
\end{bmatrix}$, **v** $\epsilon R^n$
- **c = Av** = $\begin{bmatrix}
 a_{11} * v_1 & \dots & a_{1n} * v_n \\
 \vdots & \ddots & \vdots \\
 a_{m1} * v_1 & \dots & a_{mn} * v_n
\end{bmatrix}$, **c** $\epsilon R^n$


In [6]:
def matrix_multi_vector(matrix, vector):
    result = matrix.dot(vector)
    return result

In [7]:
m = np.array([[-1, 1, 1], [0, -4, 9]])
v = np.array([0, 2, 1])
result = matrix_multi_vector(m, v)
print(result)

[3 1]


### 1.4. Multiplying a matrix by a matrix

- Matrix: A = $\begin{bmatrix}
 a_{11} & \dots & a_{1n} \\
 \vdots & \ddots & \vdots \\
 a_{m1} & \dots & a_{mn}
\end{bmatrix}$, **A** $\epsilon R^{m*n}$

- Matrix: B = $\begin{bmatrix}
 a_{11} & \dots & a_{1n} \\
 \vdots & \ddots & \vdots \\
 a_{m1} & \dots & a_{mn}
\end{bmatrix}$, **B** $\epsilon R^{n*k}$

- **C = AB** = $\begin{bmatrix}
 a_{11} * b_{11} + \dots + a_{1n} * b_{n1} & \dots & a_{11} * b_{1k} + a_{1n} * b_{nk} \\
 \vdots & \ddots & \vdots \\
 a_{m1} * b_{11} + \dots + a_{mn} * b_{n1} & \dots & a_{m1} * b_{1k} + a_{mn} * b_{nk}
\end{bmatrix}$, **C** $\epsilon R^{m*k}$


In [8]:
def matrix_multi_matrix(matrix1, matrix2):
    result = matrix1.dot(matrix2)
    return result

In [9]:
m1 = np.array([[0, 1, 2], [2, -3, 1]])
m2 = np.array([[1, -3], [6, 1], [0, -1]])
result = matrix_multi_matrix(m1, m2)
print(result)

[[  6  -1]
 [-16 -10]]


### 1.5. Matrix inverse

- Matrix A = $\begin{bmatrix}
a & b \\
c & d
\end{bmatrix}$ **A** $\epsilon R^{2*2}$
- Determinant of **A** $\epsilon R^{2*2}$: $det(A) = ad - bc$
- if $det(A) \neq 0$ **A** is invertile
- Inverse Matrix: **$A^{-1}$** = $\frac{1}{det(A)}\begin{bmatrix}
d & -b \\
-c & a
\end{bmatrix}$


In [10]:
# Dùng numpy
def inverse_matrix(matrix):
    result = np.linalg.inv(matrix)
    return result


A = [[-2, 6],
     [8, -4]]
print(inverse_matrix(A))

[[0.1  0.15]
 [0.2  0.05]]


### 2. Eigenvector and eigenvalue

- **A** $\epsilon$ $\mathbb{R}^{n*n}$, **I** (identity matrix) $\epsilon$ $\mathbb{R}^{n*n}$, **v** $\epsilon$ R^n
- Eigenvalue ($\lambda $): det(A - $\lambda $ I) = 0
- Eigenvector (**v**): Av = $\lambda $ v $\Leftrightarrow$ (A - $\lambda $ I)v = 0
- Normalize vector: $\frac{v}{\left \| v \right \|}$, v_i = $\frac{v_i}{\sqrt{\sum^n_1 v^2_i}}$


In [11]:
import numpy as np

In [12]:
def compute_eigenvalues_eigenvectors(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    return eigenvalues, eigenvectors

In [13]:
A = np.array([[0.9, 0.2],
              [0.1, 0.8]])
print(compute_eigenvalues_eigenvectors(A))

(array([1. , 0.7]), array([[ 0.89442719, -0.70710678],
       [ 0.4472136 ,  0.70710678]]))


### 3. Cosine Similarity

- Data (vector x, y): **x** = {x_1, ..., x_n} **y** = {y_1, ..., y_n}
- Cosine Similarity:
  cs(x, y) = $\frac{x . y}{\left \| x \right \| \left \| y \right \|}$
  = $\frac{\sum_{1}^{n} x_i y_i}{\sqrt{\sum_{1}^{n}x_i^2} \sqrt{\sum_{1}^{n}y_i^2}}$


In [14]:
def compute_vector_length(vector):
    len_of_vector = np.sqrt(vector.dot(vector))
    return len_of_vector


def compute_cosine(v1, v2):
    dot_product = v1.dot(v2)
    len_v1 = compute_vector_length(v1)
    len_v2 = compute_vector_length(v2)
    cos_sim = dot_product / (len_v1 * len_v2)
    return cos_sim


x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 0])
print(compute_cosine(x, y))

0.5773502691896257
