In [1]:
import torch
import torch.nn as nn

data = torch.Tensor([1, 2, 3])
softmax_function = nn.Softmax(dim=0)
output = softmax_function(data)
assert round(output[0]. item(), 2) == 0.09
output

tensor([0.0900, 0.2447, 0.6652])

In [1]:
# cau 2
import torch
import torch.nn as nn


class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        exp_x = torch.exp(x)
        sum_exp_x = torch.sum(exp_x)
        return exp_x / sum_exp_x


data = torch . Tensor([5, 2, 4])
my_softmax = MySoftmax()
output = my_softmax(data)
assert round(output[-1]. item(), 2) == 0.26
output

tensor([0.7054, 0.0351, 0.2595])

In [6]:
# cau 3
data = torch.Tensor([1, 2, 300000000])
my_softmax = MySoftmax()
output = my_softmax(data)
assert round(output[0].item(), 2) == 0.0
output

tensor([0., 0., nan])

In [7]:
# cau 4
import torch
import torch.nn as nn


class SoftmaxStable(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x_max = torch.max(x, dim=0, keepdims=True)
        x_exp = torch.exp(x - x_max.values)
        partition = x_exp.sum(0, keepdims=True)
        return x_exp / partition


data = torch.Tensor([1, 2, 3])
softmax_stable = SoftmaxStable()
output = softmax_stable(data)
assert round(output[-1].item(), 2) == 0.67
output

tensor([0.0900, 0.2447, 0.6652])

In [13]:
# cau 5, 6, 7
from abc import ABC, abstractmethod


class Person(ABC):
    def __init__(self, name: str, yob: int):
        self._name = name
        self._yob = yob

    def get_yob(self):
        return self._yob

    @abstractmethod
    def describe(self):
        return f'Name: {self._name} - YoB: {self._yob}'


class Student(Person):
    def __init__(self, name: str, yob: int, grade: str):
        super().__init__(name, yob)
        self._grade = grade

    def describe(self):
        print(f'Student - {super().describe()} - Grade: {self._grade}')


class Teacher(Person):
    def __init__(self, name: str, yob: int, subject: str):
        super().__init__(name, yob)
        self._subject = subject

    def describe(self):
        print(f'Student - {super().describe()} - Grade: {self._subject}')


class Doctor(Person):
    def __init__(self, name: str, yob: int, specialist: str):
        super().__init__(name, yob)
        self._specialist = specialist

    def describe(self):
        print(f'Student - {super().describe()} - Grade: {self._specialist}')


student1 = Student(name='studentZ2023', yob=2011, grade='6')
assert student1._yob == 2011
student1.describe()

teacher1 = Teacher(name='teacherZ2023', yob=1991, subject='History')
assert teacher1._yob == 1991
teacher1.describe()

doctor1 = Doctor(name='doctorZ2023', yob=1981, specialist='Endocrinologists')
assert doctor1._yob == 1981
doctor1.describe()

Student - Name: studentZ2023 - YoB: 2011 - Grade: 6
Student - Name: teacherZ2023 - YoB: 1991 - Grade: History
Student - Name: doctorZ2023 - YoB: 1981 - Grade: Endocrinologists


In [19]:
# cau 8
class Ward:
    def __init__(self, name):
        self.__name = name
        self.__listPeople = list()

    def add_person(self, person: Person):
        self.__listPeople.append(person)

    def descrie(self):
        print(f'Ward Name: {self.__name}')
        for p in self.__listPeople:
            p.describe()

    def count_doctor(self):
        number_doctors = 0
        for person in self.__listPeople:
            if isinstance(person, Doctor):
                number_doctors += 1
        return number_doctors


student1 = Student(name=" studentA ", yob=2010, grade="7")
teacher1 = Teacher(name=" teacherA ", yob=1969, subject=" Math ")
teacher2 = Teacher(name=" teacherB ", yob=1995, subject=" History ")
doctor1 = Doctor(name=" doctorA ", yob=1945, specialist=" Endocrinologists ")
doctor2 = Doctor(name=" doctorB ", yob=1975, specialist=" Cardiologists ")
ward1 = Ward(name=" Ward1 ")
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
assert ward1.count_doctor() == 1
ward1.add_person(doctor2)
ward1.count_doctor()

2

In [16]:
# cau 9, 10
class MyStack:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []

    def is_empty(self):
        return len(self.__stack) == 0

    def is_full(self):
        return len(self.__stack) == self.__capacity

    def push(self, value):
        if self.is_full():
            print('stack is full')
            return
        self.__stack.append(value)

    def top(self):
        return self.__stack[-1]


stack1 = MyStack(capacity=5)
stack1.push(1)
assert stack1.is_full() == False
stack1.push(2)
print(stack1.is_full())
print(stack1.top())

False
2


In [18]:
# cau 11, 12
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []

    def is_empty(self):
        return len(self.__queue) == 0

    def is_full(self):
        return len(self.__queue) == self.__capacity

    def dequeue(self):
        if self.is_empty():
            print('queue is empy')
            return
        return self.__queue.pop(0)

    def enqueue(self, value):
        if self.is_full():
            print('queue is full')
        self.__queue.append(value)

    def front(self):
        return self.__queue[0]
    
queue1 = MyQueue(capacity=5)
queue1.enqueue(1)
assert queue1.is_full() == False
queue1.enqueue(2)
print(queue1.is_full())
print(queue1.front())

False
1
